spring:
  application:
    name: miniddd
  datasource:
    url: jdbc:postgresql://localhost:5432/miniddd
    username: miniddd
    password: miniddd
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:29092
